---
- name: "Download filebeat deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb"
    dest: "files/filebeat-{{ filebeat_version }}-amd64.deb"
  register: download_filebeat
  delegate_to: localhost
  until: download_filebeat is succeeded
  when: elastic_install_type == 'remote'
- name: Copy filebeat to managed node
  copy:
    src: "files/filebeat-{{ filebeat_version }}-amd64.deb"
    mode: 0644
    dest: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
